/*
 * Created on 21 12월 2015 ( Time 14:22:53 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.app.micimpact.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "report"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="report", catalog="micimpact" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ReportEntity.countAll", query="SELECT COUNT(x) FROM ReportEntity x" )
} )
public class ReportEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="user_id", nullable=false)
    private Integer    userId       ;

    @Column(name="comment_id", nullable=false)
    private Integer    commentId    ;

    @Column(name="kind", nullable=false)
    private Integer    kind         ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date       createdAt    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ReportEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : user_id ( INT ) 
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    //--- DATABASE MAPPING : comment_id ( INT ) 
    public void setCommentId( Integer commentId ) {
        this.commentId = commentId;
    }
    public Integer getCommentId() {
        return this.commentId;
    }

    //--- DATABASE MAPPING : kind ( INT ) 
    public void setKind( Integer kind ) {
        this.kind = kind;
    }
    public Integer getKind() {
        return this.kind;
    }

    //--- DATABASE MAPPING : created_at ( TIMESTAMP ) 
    public void setCreatedAt( Date createdAt ) {
        this.createdAt = createdAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(userId);
        sb.append("|");
        sb.append(commentId);
        sb.append("|");
        sb.append(kind);
        sb.append("|");
        sb.append(createdAt);
        return sb.toString(); 
    } 

}
