<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.0 ) - Date 2015-12-09 ( Time 16:26:42 ) -->

<div>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<fieldset class="col-sm-12 bordure">
			<legend class="legende"><s:message code="report"/></legend>
		
			<util:message message="${message}" messages="${messages}" />
			
	    	<s:url value="${saveAction}" var="url_form_submit" />
			<form:form class="form-horizontal" modelAttribute="report" cssClass="well form-horizontal" method="POST" action="${url_form_submit}">
				<form:errors path="*" cssClass="alert alert-danger" element="div" />

<c:if test="${mode != 'create'}">
				<!-- Store data in hidden fields in order to be POST even if the field is disabled -->
				<form:hidden path="id" />
</c:if>
 
				<!-- PRIMARY KEY FIELD : id -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="report_id" class="col-sm-2 control-label"><s:message code="report.id"/></label>
					<div class="col-sm-10">
						<form:input id="report_id" path="id" class="form-control" maxLength="11" disabled="${mode != 'create'}" />
						<form:errors id="report_id_errors" path="id" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : userId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="report_userId" class="col-sm-2 control-label"><s:message code="report.userId"/></label>
					<div class="col-sm-10">
  						<form:input id="report_userId" path="userId" class="form-control" maxLength="11"  />
						<form:errors id="report_userId_errors" path="userId" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : commentId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="report_commentId" class="col-sm-2 control-label"><s:message code="report.commentId"/></label>
					<div class="col-sm-10">
  						<form:input id="report_commentId" path="commentId" class="form-control" maxLength="11"  />
						<form:errors id="report_commentId_errors" path="commentId" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : kind -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="report_kind" class="col-sm-2 control-label"><s:message code="report.kind"/></label>
					<div class="col-sm-10">
  						<form:input id="report_kind" path="kind" class="form-control" maxLength="11"  />
						<form:errors id="report_kind_errors" path="kind" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : createdAt -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="report_createdAt" class="col-sm-2 control-label"><s:message code="report.createdAt"/></label>
					<div class="col-sm-10">
  						<input:date id="report_createdAt" name="createdAt" />  <!-- DATE type -->
						<form:errors id="report_createdAt_errors" path="createdAt" cssClass="label label-danger" />

					</div>
				</div>

 

				<!-- ACTION BUTTONS -->
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-2">
						<c:if test="${mode != 'create'}">
							<!-- "DELETE" button ( HREF link ) -->
							<s:url var="deleteButtonURL" value="/report/delete/${report.id}" />
							<a role="button" class="btn btn-danger btn-block" href="${deleteButtonURL}"><s:message code="delete"/></a>
						</c:if>
					</div>
    				<div class="col-sm-offset-4 col-sm-2">
						<!-- "CANCEL" button ( HREF link ) -->
		 				<s:url var="cancelButtonURL" value="/report" />
						<a role="button" class="btn btn-default btn-block" href="${cancelButtonURL}"><s:message code="cancel"/></a>
					</div>
    				<div class="col-sm-2">
						<!-- "SAVE" button ( SUBMIT button ) -->
						<button type="submit" class="btn btn-primary btn-lg btn-block"><s:message code="save"/></button>
					</div>
				</div>
			</form:form>
	    </fieldset>
	</div>	
</div>
