<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.0 ) - Date 2015-12-09 ( Time 16:26:40 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>
<%@ taglib tagdir="/WEB-INF/tags/trams" prefix="trams_c"%>

	<div class="container">
		<div class="search_box admin_user">
			<div class="title">
				추천카드 관리
			</div>
		</div>
		
		<div id="card_form">
		
	    	<s:url value="${saveAction}" var="url_form_submit" />
			<form:form id="cards_form" enctype="multipart/form-data" class="form-horizontal" modelAttribute="cards" cssClass="form-horizontal" method="POST" action="${url_form_submit}/${cards.id}">
				<form:errors path="*" cssClass="alert alert-danger" element="div" />

				<c:if test="${mode != 'create'}">
				<!-- Store data in hidden fields in order to be POST even if the field is disabled -->
				<form:hidden path="id" />
				<form:hidden path="runingTime" />
				<form:hidden path="createdAt" />
				</c:if>
 
				<!-- DATA FIELD : userId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_userId" class="col-sm-2 control-label">카드 회원</label>
					<div class="col-sm-10">
  						<form:input id="cards_userId" path="userId" class="form-control" maxLength="11" />
						<form:errors id="cards_userId_errors" path="userId" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : categoryId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_categoryId" class="col-sm-2 control-label">카테고리</label>
					<div class="col-sm-10">
<%--   						<form:input id="cards_categoryId" path="categoryId" class="form-control" maxLength="11"  /> --%>
						<form:select path="categoryId" class="form-control">
							<c:forEach var="category" items="${listOfCategoriesListItem}">
				 				<form:option value="${category.value}" >${category.label}</form:option>
				 			</c:forEach>
						</form:select>
						<form:errors id="cards_categoryId_errors" path="categoryId" cssClass="label label-danger" />
						
					</div>
				</div>

 
				<!-- DATA FIELD : thumbnailUrl -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_thumbnailUrl" class="col-sm-2 control-label">첫 이미지</label>
					<div class="col-sm-10">
						<input class="file hidden" type="file" id="fileThumbnail"  name="fileThumbnail" style="background: white; border: 0;"/>
  						<form:input id="cards_thumbnailUrl" path="thumbnailUrl" class="form-control hidden" maxLength="256"  />
						<form:errors id="cards_thumbnailUrl_errors" path="thumbnailUrl" cssClass="label label-danger" />
						<c:if test="${mode != 'create'}">
							<IMG alt="" src="https://d3i0w6mgohqrwj.cloudfront.net/${cards.thumbnailUrl}" style="max-width: 100%;"/>
							<a class="btn btn-danger" href="javascript:void(0)" onclick="deleteThumbnail(this)">이미지 삭제</a>
						</c:if>
					</div>
				</div>

 
				<!-- DATA FIELD : targetUrl -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_targetUrl" class="col-sm-2 control-label">동영상 경로</label>
					<div class="col-sm-10">
  						<form:input id="cards_targetUrl" path="targetUrl" class="form-control" maxLength="256"  />
						<form:errors id="cards_targetUrl_errors" path="targetUrl" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : title -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_title" class="col-sm-2 control-label">제목</label>
					<div class="col-sm-10">
  						<form:input id="cards_title" path="title" class="form-control" maxLength="256"  />
						<form:errors id="cards_title_errors" path="title" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : actor -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_actor" class="col-sm-2 control-label">강연자</label>
					<div class="col-sm-10">
  						<form:input id="cards_actor" path="actor" class="form-control" maxLength="256"  />
						<form:errors id="cards_actor_errors" path="actor" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : body -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_body" class="col-sm-2 control-label">내용</label>
					<div class="col-sm-10">
  						<form:input id="cards_body" path="body" class="form-control" maxLength="512"  />
						<form:errors id="cards_body_errors" path="body" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : type -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_type" class="col-sm-2 control-label">파일 종류</label>
					<div class="col-sm-10">
<%--   						<form:input id="cards_type" path="type" class="form-control" maxLength="11"  /> --%>
						<form:select path="type" class="form-control">
				 			<form:option value="0" >동영상</form:option>
				 			<form:option value="1" >YouTube 동영상</form:option>
				 			<form:option value="2" >이미지(gif포함)</form:option>
						</form:select>
						<form:errors id="cards_type_errors" path="type" cssClass="label label-danger" />

					</div>
				</div>

 				<c:if test="${mode != 'create'}">
				<!-- DATA FIELD : countLike -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_countLike" class="col-sm-2 control-label">좋아요</label>
					<div class="col-sm-10">
  						<form:input id="cards_countLike" path="countLike" class="form-control" maxLength="11"  readonly="${mode != 'create'}" />
						<form:errors id="cards_countLike_errors" path="countLike" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : share -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_share" class="col-sm-2 control-label">공유</label>
					<div class="col-sm-10">
  						<form:input id="cards_share" path="share" class="form-control" maxLength="11"  readonly="${mode != 'create'}" />
						<form:errors id="cards_share_errors" path="share" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : hitCount -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_hitCount" class="col-sm-2 control-label">조회수</label>
					<div class="col-sm-10">
  						<form:input id="cards_hitCount" path="hitCount" class="form-control" maxLength="11"  readonly="${mode != 'create'}" />
						<form:errors id="cards_hitCount_errors" path="hitCount" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : commentCount -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_commentCount" class="col-sm-2 control-label">댓글수</label>
					<div class="col-sm-10">
  						<form:input id="cards_commentCount" path="commentCount" class="form-control" maxLength="11"  readonly="${mode != 'create'}" />
						<form:errors id="cards_commentCount_errors" path="commentCount" cssClass="label label-danger" />

					</div>
				</div>
				</c:if>
 
				<!-- DATA FIELD : adIs -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_adIs" class="col-sm-2 control-label">광고 활성화 여부</label>
					<div class="col-sm-10">
<%--   						<form:input id="cards_adIs" path="adIs" class="form-control" maxLength="11"  /> --%>
						<form:select path="adIs" class="form-control">
				 			<form:option value="0" >비활성화</form:option>
				 			<form:option value="1" >활성화</form:option>
						</form:select>
						<form:errors id="cards_adIs_errors" path="adIs" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : adMent -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_adMent" class="col-sm-2 control-label">광고 타이틀</label>
					<div class="col-sm-10">
  						<form:input id="cards_adMent" path="adMent" class="form-control" maxLength="128"  />
						<form:errors id="cards_adMent_errors" path="adMent" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : adLink -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_adLink" class="col-sm-2 control-label">클릭시 링크</label>
					<div class="col-sm-10">
  						<form:input id="cards_adLink" path="adLink" class="form-control" maxLength="256"  />
						<form:errors id="cards_adLink_errors" path="adLink" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : relatedCardId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_relatedCardId" class="col-sm-2 control-label">연관 카드</label>
					<div class="col-sm-10">
  						<form:input id="cards_relatedCardId" path="relatedCardId" class="form-control" maxLength="11" readonly="true"  />
						<form:errors id="cards_relatedCardId_errors" path="relatedCardId" cssClass="label label-danger" />
						<a class="btn btn-primary" href="javascript:void(0)" id="btn_search_card" style="position: absolute; right: 16px; top: 0; width: 140px;">
							카드 검색
						</a>
					</div>
				</div>

 
				<!-- DATA FIELD : relatedCardId -->
				<c:if test="${mode != 'create'}">
				<div class="form-group card_image_root">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_files" class="col-sm-2 control-label">카드 이미지</label>
					<ul class="col-sm-10">
					<c:forEach items="${images}" var="image">
						<li id="${image.id}">
							<img src="https://d3i0w6mgohqrwj.cloudfront.net/${image.imageUrl}" style="width: 50%; margin-bottom: 10px;">
							<a class="btn btn-danger" href="javascript:void(0)" onclick="deleteFile(this)">카드 이미지 삭제</a>
						</li>
					</c:forEach>
					</ul>
				</div>
				<input type="hidden" id="delete" name="delete" value=""/>
				</c:if>
			</form:form>
			
			<form:form id="file-form" enctype="multipart/form-data" modelAttribute="fileTransfer" action="/admin/manage_cards/create_files" method="POST">
				<div class="form-group card_image_root">
					<label for="cards_files" class="col-sm-2 control-label">카드 이미지 업로드</label>
					<div class="col-sm-10" id="fileInputs">
	 						<div style="margin-bottom: 10px;">* 10개까지 저장가능합니다.</div>	
						<input class="file" type="file" id="file0"  name="files[0]" style="background: white; border: 0;"/>
						<ul></ul>
					</div>
				</div>
			</form:form>
			
			
			<!-- ACTION BUTTONS -->
			<div class="form-group">
				<div class="col-sm-offset-6 col-sm-2">
					<c:if test="${mode != 'create'}">
						<!-- "DELETE" button ( HREF link ) -->
						<s:url var="deleteButtonURL" value="/admin/manage_cards/delete/${cards.id}" />
						<a role="button" class="btn btn-danger btn-lg btn-block" href="${deleteButtonURL}">카드 삭제</a>
					</c:if>
				</div>
   				<div class="col-sm-2">
					<!-- "CANCEL" button ( HREF link ) -->
	 				<s:url var="cancelButtonURL" value="/admin/manage_cards" />
					<a role="button" class="btn btn-default btn-lg btn-block" href="${cancelButtonURL}">목록</a>
				</div>
   				<div class="col-sm-2">
					<!-- "SAVE" button ( SUBMIT button ) -->
					<a class="btn btn-primary btn-lg btn-block" onclick="submitContents()">저장</a>
				</div>
			</div>
			
	    </div>
	    
		<input type="hidden" value="0" id="index"/>
	</div>	
	<s:url value="/js/cards/write.js" var="js_url_write" />
	<script type="text/javascript" src="${js_url_write}" charset="UTF-8"></script>
	<script type="text/javascript">
		$(function() {
			// thumbnail이 없을 경우
			if ($("#cards_thumbnailUrl").val() == '') {
				$("#cards_thumbnailUrl").parent().find("img").remove();
				$("#cards_thumbnailUrl").parent().find("a").remove();
				$("#fileThumbnail").removeClass("hidden");
			}
			
			// 종류 선택에 따른 카드 이미지 visible
			if ($("#type").val() == 2) {
				$(".card_image_root").css("display", "block");
			} else {
				$(".card_image_root").css("display", "none");
			}
		});
		
		$(document).on("change", "#file-form input[type='file']", function(){
			var index = $("#index").val();
			var fileId = $(this).attr('id');
			var fileIndex = fileId.split('file')[1];
			var file = pathToFile($(this).val());
			var fileName = file.name+"."+file.extension;
			var fileNameHtml = '<li style="border: 1px solid #DDDDDD; padding: 5px; background-color:#F5FAFD;">'+fileName+' <a class="btn btn_gray" href="javascript:void(0)" fileId="'+ fileId +'" onclick="deleteNewFile(this)">삭제</a></li>';
			$(this).addClass('hide');
			$("#fileInputs ul").append(fileNameHtml);
			addFileInput();
		});
		
		$( "#type" ).change(function() {
			  if (this.value == 2) {
				  $(".card_image_root").css("display", "block");
			  } else {
				  $(".card_image_root").css("display", "none");
			  }
		});

		function deleteNewFile(ele){
			var fileId = "#"+$(ele).attr('fileId');
			$(ele).parent().remove();
			$(fileId).remove();
		
			return false;
		}
		function addFileInput(){
			var index = $("#index").val();
			var newIndex = Number(index) + 1;
			$("#index").val(newIndex);
			
			var fileHtml = '<input class="file" name="files['+ newIndex +']" type="file" id="file' + newIndex + '" style="background: white; border: 0;"></input>';
			$("#fileInputs").append(fileHtml);
		}
		function pathToFile(str)
		{
		    var nOffset = Math.max(0, Math.max(str.lastIndexOf('\\'), str.lastIndexOf('/')));
		    var eOffset = str.lastIndexOf('.');
		    if(eOffset < 0)
		    {
		        eOffset = str.length;
		    }
		    return {isDirectory: eOffset == str.length,
		            path: str.substring(0, nOffset),
		            name: str.substring(nOffset > 0 ? nOffset + 1 : nOffset, eOffset),
		            extension: str.substring(eOffset > 0 ? eOffset + 1 : eOffset, str.length)};
		}
		function deleteFile(fPath){
			var delList = $("#delete").val();
			var id = $(fPath).parent().attr('id');
			if(delList != ""){
				$("#delete").val(delList+","+id);
			}else{
				$("#delete").val(id);
			}
			$(fPath).parent().remove();
			return false;
		}

		function deleteThumbnail(fPath){
// 			var delList = $("#delete").val();
// 			var id = $(fPath).parent().attr('id');
// 			if(delList != ""){
// 				$("#delete").val(delList+","+id);
// 			}else{
// 				$("#delete").val(id);
// 			}

			$("#cards_thumbnailUrl").val("");
			$(fPath).parent().find("img").remove();
			$(fPath).parent().find("a").remove();
			$("#fileThumbnail").removeClass("hidden");
			return false;
		}
		
		$("#btn_search_card").click(function() {
			popupSearchCard();
		});
		
		function popupSearchCard() {
	        var popUrl = "/admin/manage_cards/popup_search_card";
	        var popOption = "width=750, height=800, resizable=no, scrollbars=no, status=no;"; //팝업창 옵션(optoin)
	        var newWindow = window.open(popUrl, "", popOption);
	        newWindow.focus();
		}
	</script>
</div>
