<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.1 ) - Date 2015-04-29 ( Time 14:15:53 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>


<script>
    var chart;

    var chartData = [
        {
            "country": "USA",
            "visits": 4025
        },
        {
            "country": "China",
            "visits": 1882
        },
        {
            "country": "Japan",
            "visits": 1809
        },
        {
            "country": "Germany",
            "visits": 1322
        },
        {
            "country": "UK",
            "visits": 1122
        },
        {
            "country": "France",
            "visits": 1114
        },
        {
            "country": "India",
            "visits": 984
        },
        {
            "country": "Spain",
            "visits": 711
        },
        {
            "country": "Netherlands",
            "visits": 665
        },
        {
            "country": "Russia",
            "visits": 580
        },
        {
            "country": "South Korea",
            "visits": 443
        },
        {
            "country": "Canada",
            "visits": 441
        },
        {
            "country": "Brazil",
            "visits": 395
        },
        {
            "country": "Italy",
            "visits": 386
        },
        {
            "country": "Australia",
            "visits": 384
        },
        {
            "country": "Taiwan",
            "visits": 338
        },
        {
            "country": "Poland",
            "visits": 328
        }
    ];


    AmCharts.ready(function () {
        // SERIAL CHART
        chart = new AmCharts.AmSerialChart();
        chart.dataProvider = chartData;
        chart.categoryField = "country";
        chart.startDuration = 1;

        // AXES
        // category
        var categoryAxis = chart.categoryAxis;
        categoryAxis.labelRotation = 90;
        categoryAxis.gridPosition = "start";

        // value
        // in case you don't want to change default settings of value axis,
        // you don't need to create it, as one value axis is created automatically.

        // GRAPH
        var graph = new AmCharts.AmGraph();
        graph.valueField = "visits";
        graph.balloonText = "[[category]]: <b>[[value]]</b>";
        graph.type = "column";
        graph.lineAlpha = 0;
        graph.fillAlphas = 0.8;
        chart.addGraph(graph);

        // CURSOR
        var chartCursor = new AmCharts.ChartCursor();
        chartCursor.cursorAlpha = 0;
        chartCursor.zoomable = false;
        chartCursor.categoryBalloonEnabled = false;
        chart.addChartCursor(chartCursor);

        chart.creditsPosition = "top-right";

        chart.write("chartdiv");
    });
</script>


	<div class="container">
		<div style="float: left">
			<div class="list-group">
				<a href="/admin/statistics_1" class="list-group-item active">그래프_1</a>
				<a href="/admin/statistics_2" class="list-group-item">그래프_2</a>
				<a href="/admin/statistics_3" class="list-group-item">그래프_3</a>
			</div>
		</div>
		
		<div style="width: 700px; float: left; margin-left: 30px;">
			<div style="margin-bottom: 25px;">
				 <legend class="legende">그래프_1</legend>
			</div>
			
			<div id="chartdiv" style="width: 100%; height: 400px;"></div>
		</div>
		
	</div>	
	
</div>
