<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.0 ) - Date 2015-12-09 ( Time 16:26:40 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>
<%@ taglib tagdir="/WEB-INF/tags/display" prefix="display"%>
<%@ taglib tagdir="/WEB-INF/tags/trams" prefix="trams_c"%>

	<div class="container">
	
		<div class="search_box admin_user">
		<FORM method="post" >
			<div class="title" style="border-bottom:0px">
			   	<SPAN>채널 제목</SPAN>
			   	<SPAN style="margin-left: 30%">채널 소개 글</SPAN>
			   	<button type="submit" name="edit" value="1" style="float:right" class="btn btn-default" >저장하기</button>
			</div>
			<div class="title" style="border-bottom:0px">
			   	<div class="input-group" style=" display: inline-block; vertical-align: top; ">
					<input type="text" name="title" class="form-control" value="${c.title}"  >
				</div>
				<div class="input-group" style=" display: inline-block; vertical-align: left;margin-left: 23% ">
					<TEXTAREA type="text" name="introduce" class="form-control" placeholder=""  rows="3" cols="60">${c.introduce}</TEXTAREA>
				</div>
				<div class="input-group" style=" display: inline-block; vertical-align: top;margin-left: 10% ">
					<span class="glyphicon glyphicon-heart"></span> ${c.likes}
				</div>
			</div>
			</FORM>
			<FORM id="form_search" method="get" >
			<div class="form-inline">
				<div class="form_group">
					<select class="form-control" name="opition" id="option">
					<c:if test="${opition==0 }">
						<option value="0" selected="selected">선택</option>
					</c:if>
						<c:if test="${opition!=0 }">
						<option value="0">선택</option>
					</c:if>
						<c:if test="${opition==1 }">
							<option value="1" selected="selected">제목</option>
						</c:if>
						<c:if test="${opition!=1 }">
							<option value="1">제목</option>
						</c:if>
					</select>
					
					<select class="form-control" name="order" onchange="$('#form_search').submit()"  id="sort_select">
						<c:if test="${order!='title' }">
							<option value="title">제목별</option>
						</c:if>
						<c:if test="${order=='title' }">
							<option value="title" selected="selected">제목별</option>
						</c:if>
						<c:if test="${order=='createdAt' }">
							<option value="createdAt" selected="selected">생성일별</option>
						</c:if>
						<c:if test="${order!='createdAt' }">
							<option value="createdAt">생성일별</option>
						</c:if>
					</select>
				
					<div class="input-group">
						<span class="input-group-addon" id="sizing-addon1">
							<span class="glyphicon glyphicon-search"></span>
						</span>
						<input type="text" value="${key }" name="keyword" class="form-control" placeholder="" >
						<span class="input-group-btn">
							<button class="btn btn-default" type="submit" >검색</button>
						</span>
					</div><!-- /input-group -->
				</div>
			</div><!-- /.row -->
			</FORM>
		</div>
	
		<util:message message="${message}" messages="${messages}" />

		<table class="table table-striped">
			<thead>
				<tr>
					<th width="10%">카드번호</th>
					<th width="60%">제목</th>
					<th width="20%">생성일</th>
					<s:url var="url_create" value="/admin/channel/card/form?channel_id=${c.id }" />
					<th width="10%"><a class="btn btn-info" href='${url_create}'>카드추가</a></th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${list}" var="cards">
					<tr>
						<s:url var="url_update" value="/admin/manage_cards/form/${cards.id}	"/>
						<td>${cards.id}</td>
						<td><a href="${url_update}">${cards.title}</a></td>
						<td><display:date value="${cards.createdAt}" /></td>
						<td>
						<c:url var="delete_card" value="/admin/manage_chanels/card/delete/${c.id}/${cards.id}" />
						<a class="btn btn-danger" href="${delete_card }" >삭제</a>
						</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		<div class="col-sm-offset-11">
			<c:url var="delete_channel" value="/admin/manage_chanels/delete/${c.id}" />
			<a href="${delete_channel}" class="btn btn-danger" >돌아가기 </a>
		</div>
		<trams_c:pagnation currentIndex="${currentIndex}" url="${url}" totalPages="${page.totalPages}" id="" />
	</div>
</div>