<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.0 ) - Date 2015-12-09 ( Time 16:26:40 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>
<%@ taglib tagdir="/WEB-INF/tags/display" prefix="display"%>
<%@ taglib tagdir="/WEB-INF/tags/trams" prefix="trams_c"%>
<c:url value="/" var="root"></c:url>
<script src="${root}js/jquery.js"></script>
	<div class="container">
		<div class="search_box admin_user">
			<div class="title">
				카드관리
			</div>
			
			<div class="text-right">
				<div class="" style="display: inline-block; vertical-align; middle;">
						<!-- Nav tabs -->
					  <ul class="nav nav-tabs" role="tablist">
					    <li role="presentation" class="${active_day}"><a href="#daily" aria-controls="home" role="tab" data-toggle="tab">일간</a></li>
					    <li role="presentation" class="${active_week}"><a href="#weekly" aria-controls="profile" role="tab" data-toggle="tab">주간</a></li>
					    <li role="presentation" class="${active_month}"><a href="#monthly" aria-controls="messages" role="tab" data-toggle="tab">월간</a></li>
					  </ul>
					
					  <!-- Tab panes -->
					  <div class="tab-content">
						 <div role="tabpanel" class="tab-pane ${active_day}" id="daily">
						 	<div class="date-picker micimpact_picker">&#160;</div>
						 </div>
						 <div role="tabpanel" class="tab-pane ${active_week}" id="weekly">
						 	<div class="week-picker micimpact_picker">&#160;</div>
						 </div>
						 <div role="tabpanel" class="tab-pane ${active_month}" id="monthly">
						 	<div class="month-picker micimpact_picker">&#160;</div>
						 </div>
			  		</div>
			  	</div>
		  </div>
		  
		  <form method="get" id="stats_form">
		  	<input type="text" style="display:none" name="day" value="${day }" id="day"></input>
		  	<input type="text" style="display:none" name="startDate" value="${startDate }" id="startDate"></input>
		  	<input type="text" style="display:none" name="endDate" value="${endDate }" id="endDate"></input>
		  	<input type="text" style="display:none" name="month" value="${month }" id="month"></input>
		  	<input type="text" style="display:none" name="year" value="${year}" id="year"></input>
		  </form>
		  
			<div class="title" style="padding: 0px 0;border-bottom: 0px " >
				통계기간 : ${title }
			</div>
			
			<table class="table  table-bordered">
  				<tr>
    				<td colspan="3">${header_table}</td>
  				</tr>
  				<tr>
    				<td rowspan="2">통계현황</td>
    				<td>회원가입</td>
    				<td>${count_join}</td>
  				</tr>
  				<tr>
    				<td>컨텐츠 조회수</td>
    				<td>${count_view }</td>
  				</tr>
			</table>	

			<div class="title" style="padding: 0px 0">
				&#160;
			</div>	
			
			
			<div class="form-inline">
				<div class="form_group">
					<span style="font-size:20px;" >랭킹</span>
					<select class="form-control" id="sort_select" name="order">
					<c:if test="${order=='hitCount'}">
						<option value="view" selected="selected">조회수</option>
					</c:if>
					<c:if test="${order!='hitCount'}">
						<option value="view" >조회수</option>
					</c:if>
					<c:if test="${order=='like'}">
						<option value="like" selected="selected">좋아요</option>
					</c:if>
					<c:if test="${order!='like'}">
						<option value="like">좋아요</option>
					</c:if>
					<c:if test="${order=='comment'}">
						<option value="comment" selected="selected">댓글</option>
					</c:if>
					<c:if test="${order!='comment'}">
						<option value="comment">댓글</option>
					</c:if>	
					<c:if test="${order=='share'}">
						<option value="share" selected="selected">공유</option>
					</c:if>
					<c:if test="${order!='share'}">
						<option value="share">공유</option>
					</c:if>		
						
						
					</select>
				</div>
			</div><!-- /.row -->
		</div>

		<util:message message="${message}" messages="${messages}" />

		<table class="table table-striped">
			<thead>
				<tr>
					<th width="10%">카드번호</th>
					<th width="60%">제목</th>
					<th width="20%">생성일</th>
					<th width="10%">&#160;</th>
				</tr>
			</thead>
			<tbody>
			<form method="post" id="card_form">
				<c:forEach items="${list}" var="cards">
					<tr>
						<s:url var="url_update" value="/admin/manage_cards/form/${cards.id}"/>
						<td>${cards.id}</td>
						<td><a href="${url_update}">${cards.title}</a></td>
						<td><display:date value="${cards.createdAt}" /></td>
						<td><a class="btn btn-danger" href="javascript:void(0)" onclick="deleteCard(${cards.id})">삭제</a></td>
					</tr>
				</c:forEach>
				<INPUT type="text" class="hidden" name="delete" value="" id="card_delete"/>
			</form>
			</tbody>
		</table>
		<trams_c:pagnation currentIndex="${currentIndex}" url="${url}" totalPages="${page.totalPages}" id="" />
			
		<SCRIPT type="text/javascript">
			function deleteCard(id) {
				if (confirm("삭제하시겠습니까?")) {
					$('#card_delete').val(id);
					$('#card_form').submit();
				}
			}

			$('#sort_select').change(function(){
				location.href = "${root}admin/stats?order="+$('#sort_select').val();
			});
			
		</SCRIPT>
		
	</div>
</div>