/*
 * Created on 21 12월 2015 ( Time 19:53:39 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service;

import java.util.List;

import com.app.micimpact.bean.CardTags;

/**
 * Business Service Interface for entity CardTags.
 */
public interface CardTagsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	CardTags findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<CardTags> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CardTags save(CardTags entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CardTags update(CardTags entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CardTags create(CardTags entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	List<CardTags> findByCardIdIn(Integer card_ids[]);
	void deleteByCardId(Integer card_id);
	void    deleteByChannelId(Integer channel_id);
}
