/*
 * Created on 9 12월 2015 ( Time 17:41:09 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.app.micimpact.bean.Categories;
import com.app.micimpact.bean.jpa.CategoriesEntity;

/**
 * Business Service Interface for entity Categories.
 */
public interface CategoriesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Categories findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Categories> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Categories save(Categories entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Categories update(Categories entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Categories create(Categories entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<CategoriesEntity> findAll(Integer page,Integer size);
}
