/*
 * Created on 21 Mar 2016 ( Time 16:47:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.app.micimpact.business.service;

import java.util.List;

import com.app.micimpact.bean.ChannelLike;
import com.app.micimpact.bean.jpa.ChannelLikeEntity;

/**
 * Business Service Interface for entity ChannelLike.
 */
public interface ChannelLikeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ChannelLike findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ChannelLike> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ChannelLike save(ChannelLike entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ChannelLike update(ChannelLike entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ChannelLike create(ChannelLike entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	List<ChannelLikeEntity> findByUserIdAndChannelId(Integer userId,Integer channeId);
	
	List<ChannelLikeEntity> findByUserId(Integer userId);
}
