/*
 * Created on 9 12월 2015 ( Time 17:41:16 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service;

import java.util.List;

import com.app.micimpact.bean.Collections;

/**
 * Business Service Interface for entity Collections.
 */
public interface CollectionsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Collections findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Collections> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Collections save(Collections entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Collections update(Collections entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Collections create(Collections entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Collections findByReveal();
}
