/*
 * Created on 28 12월 2015 ( Time 15:48:18 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service;

import java.util.List;

import com.app.micimpact.bean.CommentLikes;

/**
 * Business Service Interface for entity CommentLikes.
 */
public interface CommentLikesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	CommentLikes findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<CommentLikes> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CommentLikes save(CommentLikes entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CommentLikes update(CommentLikes entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CommentLikes create(CommentLikes entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	CommentLikes findByUserIdAndCardIdAndCommentId(Integer userId, Integer cardId, Integer commentId);
}
