/*
 * Created on 21 12월 2015 ( Time 20:17:00 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.app.micimpact.bean.IntialTags;
import com.app.micimpact.bean.jpa.IntialTagsEntity;

/**
 * Business Service Interface for entity IntialTags.
 */
public interface IntialTagsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	IntialTags findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<IntialTags> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	IntialTags save(IntialTags entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	IntialTags update(IntialTags entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	IntialTags create(IntialTags entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<IntialTagsEntity> findAll(Integer page,Integer size);

}
