/*
 * Created on 9 12월 2015 ( Time 17:43:36 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service;

import java.util.List;
import com.app.micimpact.bean.MIList;

/**
 * Business Service Interface for entity List.
 */
public interface ListService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	MIList findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<MIList> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MIList save(MIList entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MIList update(MIList entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MIList create(MIList entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
