/*
 * Created on 13 5�� 2015 ( Time 19:15:54 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service;

import java.util.List;

import org.springframework.data.domain.Page;

import com.app.micimpact.bean.Locales;
import com.app.micimpact.bean.jpa.LocalesEntity;

/**
 * Business Service Interface for entity Locales.
 */
public interface LocalesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Locales findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Locales> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Locales save(Locales entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Locales update(Locales entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Locales create(Locales entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<LocalesEntity> findAll(Integer pageNumber);
	Page<LocalesEntity> findSearchAll(Integer pageNumber, Integer option, String keyword);
}
