/*
 * Created on 13 5월 2015 ( Time 11:43:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.app.micimpact.business.service;

import java.util.Date;
import java.util.List;

import org.springframework.data.domain.Page;

import com.app.micimpact.bean.Users;
import com.app.micimpact.bean.jpa.UsersEntity;

/**
 * Business Service Interface for entity Users.
 */
public interface UsersService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Users findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Users> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Users save(Users entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Users update(Users entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Users create(Users entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	
	Users checkUser(String username);
	
	Users checkSnsUser(String token, String type);

	Users findUser(Users users, Integer option);

	Page<UsersEntity> findAll(Integer pageNumber, Integer state);

	Page<UsersEntity> findSearchAll(Integer pageNumber, Integer option, String keyword);

	List<Users> findByListLimit(int i);

	Users findByEmail(String email);

	Users findByEmailAndName(String email, String name);
	
	List<Users> findByIdIn(Integer[] ids);

	void updatePointLevel(Integer point,  Integer level, Integer user_id);
	
	Integer countJoinUser_ByDay(Date createAT);
	
	Integer countJoinUser_ByWeek(Date start, Date end);
	
	Integer countJoinUser_ByMonth(Integer month, Integer year);
	
	Integer totalJoinUsery();
	
	
}
