<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.1 ) - Date 2015-04-30 ( Time 14:31:38 ) -->

<div>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<div class="reserved_box">
			<div class="search_user_box input_form">
				<form method="post" id="search_id_form">
					<table border="0" cellpadding="0" cellspacing="0" width="100%" >
						<tr>
							<th class="title" colspan="2">
								<s:message code="reserved.lostId_title"/>
							</th>
						</tr>
						<tr id="de">
							<th width="20%"><s:message code="common.name"/></th>
							<td width="80%"><input type="text" name="name" class="in_te"/></td>
						</tr>
						<tr id="phone">
							<th><s:message code="reserved.phone"/></th>
							<td><input type="text" name="phone" class="in_te"/></td>
						</tr>
						<tr id="mail">
							<th><s:message code="common.email"/></th>
							<td>
								<ul class="join_ul" style="margin: 0; padding: 0; margin-left: 5px;">
									<li><input type="text" name="mail1"></li>
									<li class="at">@</li>
									<li><input type="text" name="mail2" class="i_mail" id="mail2"></li>
								</ul>
							</td>
						</tr>
					</table>
				</form>
				<div class="btn_gp">
					<a href="#none" class="default-btn" id="btn_id_search"><s:message code="reserved.btn_serchID"/></a>
					<a href="/login" class="default-btn btn_cancel"><s:message code="reserved.btn_back"/></a>
				</div>
				
			</div>
			<div class="search_pass_box input_form">
				<form method="post" id="search_pass_form">
					<table border="0" cellpadding="0" cellspacing="0" width="100%" >
						<tr>
							<th class="title" colspan="2">
								<s:message code="reserved.lostPassword_title"/>
							</th>
						</tr>
						<tr id="de">
							<th width="20%"><s:message code="common.name"/></th>
							<td width="80%"><input type="text" name="name1" class="in_te"/></td>
						</tr>
						<tr id="de">
							<th width="20%"><s:message code="common.id"/></th>
							<td width="80%"><input type="text" name="username" class="in_te"/></td>
						</tr>
						<tr id="phone">
							<th><s:message code="reserved.phone"/></th>
							<td><input type="text" name="phone1" class="in_te"/></td>
						</tr>
						<tr id="mail">
							<th><s:message code="common.email"/></th>
							<td>
								<ul class="join_ul" style="margin: 0; padding: 0; margin-left: 5px;">
									<li><input type="text" name="mail11"></li>
									<li class="at">@</li>
									<li><input type="text" name="mail21" class="p_mail" id="mail2"></li>
								</ul>
							</td>
						</tr>
					</table>
				</form>
				<div class="btn_gp">
					<a href="#none" class="default-btn" id="btn_pw_search"><s:message code="reserved.btn_serchPW"/></a>
					<a href="/login" class="default-btn btn_cancel"><s:message code="reserved.btn_back"/></a>
				</div>
			</div>	
		</div>
	</div>	
	<SCRIPT type="text/javascript">
		$(function(){
			$("#btn_id_search").click(function(){
				var regExp = /^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$/;
				var name = $("#search_id_form input[name=name]").val();
				var phone = $("#search_id_form  input[name=phone]").val();
				var mail1 = $("#search_id_form  input[name=mail1]").val();
				var mail2 = $("#search_id_form  input[name=mail2]").val();
				var mail = mail1+"@"+mail2
				
				if(name.length == 0){
					alert('이름을 입력해주세요.');
					document.getElementsByName("name")[0].focus();
					return false;
				}else if(phone.length == 0) {
					alert('핸드폰번호를 입력해주세요.');
					document.getElementsByName("phone")[0].focus();
					return false;
				}else if ( !regExp.test(phone)) {
					alert("잘못된 휴대폰 번호입니다. 다시입력해주세요.");
					document.getElementsByName("phone")[0].focus();
					return false
				}else if (mail1.length == 0) {
					alert("메일 앞자리를 입력해주세요.");
					document.getElementsByName("mail1")[0].focus();
					return false
				}else if (mail2.length == 0) {
					alert("메일 주소를 입력해주세요.");
					document.getElementsByName("mail2")[0].focus();
					return false
				}else if(!fn_emailChk(mail)){
					alert('이메일형식이 맞지 않습니다.');
					document.getElementsByName("mail1")[0].focus();
					return false;
				}
				
				$.ajax({
					type:"POST",
					url:"/serarchId",
					data: $('#search_id_form').serialize(),
					success:function(result) {
						if(result != "false"){
							alert(result);
						}else{
							alert("오류입니다. 관리자에게 문의해주시기 바랍니다.");
						}
					},
					error:function(request,status,error){
						alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
						//alert("통신오류가 발생하였습니다. 재시도 해주세요.");
					}
				});	
			});
			
			$("#btn_pw_search").click(function(){				
				
				var regExp = /^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$/;
				var name = $("#search_pass_form input[name=name1]").val();
				var username = $("#search_pass_form input[name=username]").val();
				var phone = $("#search_pass_form  input[name=phone1]").val();
				var mail1 = $("#search_pass_form  input[name=mail11]").val();
				var mail2 = $("#search_pass_form  input[name=mail21]").val();
				var mail = mail1+"@"+mail2
				
				if(name.length == 0){
					alert('이름을 입력해주세요.');
					document.getElementsByName("name1")[0].focus();
					return false;
				}else if(username.length == 0) {
					alert('아이디를 입력해주세요.');
					document.getElementsByName("username")[0].focus();
					return false;
				}else if(phone.length == 0) {
					alert('핸드폰번호를 입력해주세요.');
					document.getElementsByName("phone1")[0].focus();
					return false;
				}else if ( !regExp.test(phone)) {
					alert("잘못된 휴대폰 번호입니다. 다시입력해주세요.");
					document.getElementsByName("phone1")[0].focus();
					return false
				}else if (mail1.length == 0) {
					alert("메일 앞자리를 입력해주세요.");
					document.getElementsByName("mail11")[0].focus();
					return false
				}else if (mail2.length == 0) {
					alert("메일 주소를 입력해주세요.");
					document.getElementsByName("mail21")[0].focus();
					return false
				}else if(!fn_emailChk(mail)){
					alert('이메일형식이 맞지 않습니다.');
					document.getElementsByName("mail11")[0].focus();
					return false;
				}
				
				$.ajax({
					type:"POST",
					url:"/changePassword",
					data: $('#search_pass_form').serialize(),
					success:function(result) {
						var obj = JSON.parse(result);
						if(obj.success == "true"){
							alert(obj.message + "로 새로운 비밀번호를 전송하였습니다.");
						}else{
							alert(obj.message);
						}
					},
					error:function(request,status,error){
						alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
						//alert("통신오류가 발생하였습니다. 재시도 해주세요.");
					}
				});	
			});
			
		});
	
	</SCRIPT>
</div>