/*
 * Created on 21 Mar 2016 ( Time 16:47:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.app.micimpact.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class ChannelFavorite implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer channelId;

    @NotNull
    private Integer userId;

    @NotNull
    private Date createdAt;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setChannelId( Integer channelId ) {
        this.channelId = channelId;
    }
    public Integer getChannelId() {
        return this.channelId;
    }

    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setCreatedAt( Date createdAt ) {
        this.createdAt = createdAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(channelId);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(createdAt);
        return sb.toString(); 
    } 


}
