/*
 * Created on 30 Mar 2016 ( Time 16:05:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.app.micimpact.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Channel implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer userId;

    @Size( max = 300 )
    private String title;

    @Size( max = 500 )
    private String introduce;


    private Integer likes;


    private Integer favorite;


    private Integer isShow;


    private Integer isLiked;


    private Integer isFavorited;


    private Integer type;


    private Date createdAt;


    private Integer cardsRecentId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setTitle( String title ) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }

    public void setIntroduce( String introduce ) {
        this.introduce = introduce;
    }
    public String getIntroduce() {
        return this.introduce;
    }

    public void setLikes( Integer likes ) {
        this.likes = likes;
    }
    public Integer getLikes() {
        return this.likes;
    }

    public void setFavorite( Integer favorite ) {
        this.favorite = favorite;
    }
    public Integer getFavorite() {
        return this.favorite;
    }

    public void setIsShow( Integer isShow ) {
        this.isShow = isShow;
    }
    public Integer getIsShow() {
        return this.isShow;
    }

    public void setIsLiked( Integer isLiked ) {
        this.isLiked = isLiked;
    }
    public Integer getIsLiked() {
        return this.isLiked;
    }

    public void setIsFavorited( Integer isFavorited ) {
        this.isFavorited = isFavorited;
    }
    public Integer getIsFavorited() {
        return this.isFavorited;
    }

    public void setType( Integer type ) {
        this.type = type;
    }
    public Integer getType() {
        return this.type;
    }

    public void setCreatedAt( Date createdAt ) {
        this.createdAt = createdAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCardsRecentId( Integer cardsRecentId ) {
        this.cardsRecentId = cardsRecentId;
    }
    public Integer getCardsRecentId() {
        return this.cardsRecentId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(introduce);
        sb.append("|");
        sb.append(likes);
        sb.append("|");
        sb.append(favorite);
        sb.append("|");
        sb.append(isShow);
        sb.append("|");
        sb.append(isLiked);
        sb.append("|");
        sb.append(isFavorited);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(createdAt);
        sb.append("|");
        sb.append(cardsRecentId);
        return sb.toString(); 
    } 


}
