/*
 * Created on 21 12월 2015 ( Time 14:20:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Comments implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer cardId;

    @NotNull
    private Integer userId;

    @Size( max = 255 )
    private String body;

    @NotNull
    private Date createdAt;


    private Integer countLike;

    private Boolean is_like;
    
    private String user_name;

    private Integer isShow;


    private Integer countReport;
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCardId( Integer cardId ) {
        this.cardId = cardId;
    }
    public Integer getCardId() {
        return this.cardId;
    }

    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setBody( String body ) {
        this.body = body;
    }
    public String getBody() {
        return this.body;
    }

    public void setCreatedAt( Date createdAt ) {
        this.createdAt = createdAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCountLike( Integer countLike ) {
        this.countLike = countLike;
    }
    public Integer getCountLike() {
        return this.countLike;
    }

    public void setIsLike( Boolean is_like ) {
        this.is_like = is_like;
    }
    public Boolean getIsLike() {
        return this.is_like;
    }
    
    public void setUserName( String user_name ) {
        this.user_name = user_name;
    }
    public String getUserName() {
        return this.user_name;
    }
    
    public void setIsShow( Integer isShow ) {
        this.isShow = isShow;
    }
    public Integer getIsShow() {
        return this.isShow;
    }

    public void setCountReport( Integer countReport ) {
        this.countReport = countReport;
    }
    public Integer getCountReport() {
        return this.countReport;
    }
    public String getCreatedAtTime()
    {
    	SimpleDateFormat format = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");
    	return format.format(createdAt);
    }
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(cardId);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(body);
        sb.append("|");
        sb.append(createdAt);
        sb.append("|");
        sb.append(countLike);
        return sb.toString(); 
    } 


}
