/*
 * Created on 21 12월 2015 ( Time 14:20:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;
import java.util.List;

public class PageReport implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
   
    private List<ReportComment> list;
    
    private Integer currentIndex;
    
    private Integer totalPages;

	public List<ReportComment> getList() {
		return list;
	}

	public void setList(List<ReportComment> list) {
		this.list = list;
	}

	public Integer getCurrentIndex() {
		return currentIndex;
	}

	public void setCurrentIndex(Integer currentIndex) {
		this.currentIndex = currentIndex;
	}

	public Integer getTotalPages() {
		return totalPages;
	}

	public void setTotalPages(Integer totalPages) {
		this.totalPages = totalPages;
	}


   


}
