/*
 * Created on 4 May 2015 ( Time 15:47:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.app.micimpact.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Postings implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
   
    @Size( min = 1, max = 512 )
    private String title;

    @NotNull
    @Size( min = 1, max = 65535 )
    private String body;

    @NotNull
    private Date createdAt;

    @NotNull
    private Date updatedAt;


    private Boolean isSecret;


    private Integer parentId;

    @NotNull
    private Integer typeId;

    @NotNull
    private Integer userId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTitle( String title ) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }

    public void setBody( String body ) {
        this.body = body;
    }
    public String getBody() {
        return this.body;
    }

    public void setCreatedAt( Date createdAt ) {
        this.createdAt = createdAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setUpdatedAt( Date updatedAt ) {
        this.updatedAt = updatedAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setIsSecret( Boolean isSecret ) {
        this.isSecret = isSecret;
    }
    public Boolean getIsSecret() {
        return this.isSecret;
    }

    public void setParentId( Integer parentId ) {
        this.parentId = parentId;
    }
    public Integer getParentId() {
        return this.parentId;
    }

    public void setTypeId( Integer typeId ) {
        this.typeId = typeId;
    }
    public Integer getTypeId() {
        return this.typeId;
    }

    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public String getCreatedAtTime()
    {
    	SimpleDateFormat format = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");
    	return format.format(createdAt);
    }
    
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(title);
        // attribute 'body' not usable (type = String Long Text)
        sb.append("|");
        sb.append(createdAt);
        sb.append("|");
        sb.append(updatedAt);
        sb.append("|");
        sb.append(isSecret);
        sb.append("|");
        sb.append(parentId);
        sb.append("|");
        sb.append(typeId);
        sb.append("|");
        sb.append(userId);
        return sb.toString(); 
    } 


}
