/*
 * Created on 21 12월 2015 ( Time 14:20:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class ReportComment implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer commentId;

    @NotNull
    private String name;

    @NotNull
    private String body;
    
    @NotNull
    private Integer isShow;
    
    
    @NotNull
    private Integer report;



    public Integer getIsShow() {
		return isShow;
	}

	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	//----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }



    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBody() {
		return body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public void setCommentId( Integer commentId ) {
        this.commentId = commentId;
    }
    public Integer getCommentId() {
        return this.commentId;
    }

    public void setReport( Integer kind ) {
        this.report = kind;
    }
    public Integer getReport() {
        return this.report;
    }

   

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(commentId);
        sb.append("|");
        sb.append(report);
        return sb.toString(); 
    } 


}
