/*
 * Created on 31 Mar 2016 ( Time 15:32:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.app.micimpact.bean;

import java.io.Serializable;

import javax.persistence.Column;
import javax.validation.constraints.*;

import org.springframework.security.core.GrantedAuthority;

import com.app.micimpact.bean.UserRoles;
import com.app.micimpact.security.Role;

import java.util.Collection;
import java.util.Date;
import java.util.List;

public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer roleId;

    @NotNull
    @Size( min = 1, max = 256 )
    private String password;

    @NotNull
    @Size( min = 1, max = 255 )
    private String name;

    @Size( max = 255 )
    private String email;

    @NotNull
    private Date createdAt;

    @NotNull
    private Date updatedAt;


    private Integer fag;

    @Size( max = 256 )
    private String facebookToken;

    @Size( max = 256 )
    private String kakaotalkToken;

    @Size( max = 256 )
    private String lineToken;

    @Size( max = 4 )
    private String birthyear;

    @Size( max = 1 )
    private String sex;

    @Size( max = 32 )
    private String job;

    @Size( max = 32 )
    private String city;


    private Integer activityPoint;


    private Integer level;


    private Integer point;

    @Size( max = 65535 )
    private String deviceIosId;

    @Size( max = 65535 )
    private String applicantAndroidId;


    private Integer pushState;

    @Size( max = 128 )
    private String profileUrl;


    private Integer isWithdrawn;


    private Integer heartStateId;


    private Integer recentCardId;

    //----------------------------------------------------------------------
    // For spring security
    //----------------------------------------------------------------------
    private UserRoles userRoles;
    private List<Role> authorities;
    private boolean accountNonExpired = true;
    private boolean accountNonLocked = true;
    private boolean credentialsNonExpired = true;
    private boolean enabled = true;
    
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return this.authorities;
    }

    public void setAuthorities(List<Role> authorities) {
        this.authorities = authorities;
    }

    public boolean isAccountNonExpired() {
        return this.accountNonExpired;
    }

    public void setAccountNonExpired(boolean accountNonExpired) {
        this.accountNonExpired = accountNonExpired;
    }

    public boolean isAccountNonLocked() {
        return this.accountNonLocked;
    }

    public void setAccountNonLocked(boolean accountNonLocked) {
        this.accountNonLocked = accountNonLocked;
    }

    public boolean isCredentialsNonExpired() {
        return this.credentialsNonExpired;
    }

    public void setCredentialsNonExpired(boolean credentialsNonExpired) {
        this.credentialsNonExpired = credentialsNonExpired;
    }

    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public UserRoles getUserRoles() {
		return userRoles;
	}

	public void setUserRoles(UserRoles userRoles) {
		this.userRoles = userRoles;
	} 
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRoleId( Integer roleId ) {
        this.roleId = roleId;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }

    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setCreatedAt( Date createdAt ) {
        this.createdAt = createdAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setUpdatedAt( Date updatedAt ) {
        this.updatedAt = updatedAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setFag( Integer fag ) {
        this.fag = fag;
    }
    public Integer getFag() {
        return this.fag;
    }

    public void setFacebookToken( String facebookToken ) {
        this.facebookToken = facebookToken;
    }
    public String getFacebookToken() {
        return this.facebookToken;
    }

    public void setKakaotalkToken( String kakaotalkToken ) {
        this.kakaotalkToken = kakaotalkToken;
    }
    public String getKakaotalkToken() {
        return this.kakaotalkToken;
    }

    public void setLineToken( String lineToken ) {
        this.lineToken = lineToken;
    }
    public String getLineToken() {
        return this.lineToken;
    }

    public void setBirthyear( String birthyear ) {
        this.birthyear = birthyear;
    }
    public String getBirthyear() {
        return this.birthyear;
    }

    public void setSex( String sex ) {
        this.sex = sex;
    }
    public String getSex() {
        return this.sex;
    }

    public void setJob( String job ) {
        this.job = job;
    }
    public String getJob() {
        return this.job;
    }

    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }

    public void setActivityPoint( Integer activityPoint ) {
        this.activityPoint = activityPoint;
    }
    public Integer getActivityPoint() {
        return this.activityPoint;
    }

    public void setLevel( Integer level ) {
        this.level = level;
    }
    public Integer getLevel() {
        return this.level;
    }

    public void setPoint( Integer point ) {
        this.point = point;
    }
    public Integer getPoint() {
        return this.point;
    }

    public void setDeviceIosId( String deviceIosId ) {
        this.deviceIosId = deviceIosId;
    }
    public String getDeviceIosId() {
        return this.deviceIosId;
    }

    public void setApplicantAndroidId( String applicantAndroidId ) {
        this.applicantAndroidId = applicantAndroidId;
    }
    public String getApplicantAndroidId() {
        return this.applicantAndroidId;
    }

    public void setPushState( Integer pushState ) {
        this.pushState = pushState;
    }
    public Integer getPushState() {
        return this.pushState;
    }

    public void setProfileUrl( String profileUrl ) {
        this.profileUrl = profileUrl;
    }
    public String getProfileUrl() {
        return this.profileUrl;
    }

    public void setIsWithdrawn( Integer isWithdrawn ) {
        this.isWithdrawn = isWithdrawn;
    }
    public Integer getIsWithdrawn() {
        return this.isWithdrawn;
    }

    public void setHeartStateId( Integer heartStateId ) {
        this.heartStateId = heartStateId;
    }
    public Integer getHeartStateId() {
        return this.heartStateId;
    }

    public void setRecentCardId( Integer recentCardId ) {
        this.recentCardId = recentCardId;
    }
    public Integer getRecentCardId() {
        return this.recentCardId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(roleId);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(createdAt);
        sb.append("|");
        sb.append(updatedAt);
        sb.append("|");
        sb.append(fag);
        sb.append("|");
        sb.append(facebookToken);
        sb.append("|");
        sb.append(kakaotalkToken);
        sb.append("|");
        sb.append(lineToken);
        sb.append("|");
        sb.append(birthyear);
        sb.append("|");
        sb.append(sex);
        sb.append("|");
        sb.append(job);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(activityPoint);
        sb.append("|");
        sb.append(level);
        sb.append("|");
        sb.append(point);
        // attribute 'deviceIosId' not usable (type = String Long Text)
        // attribute 'applicantAndroidId' not usable (type = String Long Text)
        sb.append("|");
        sb.append(pushState);
        sb.append("|");
        sb.append(profileUrl);
        sb.append("|");
        sb.append(isWithdrawn);
        sb.append("|");
        sb.append(heartStateId);
        sb.append("|");
        sb.append(recentCardId);
        return sb.toString(); 
    } 


}
