/*
 * Created on 4 May 2015 ( Time 15:44:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.app.micimpact.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
