/*
 * Created on 28 Apr 2015 ( Time 15:46:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.app.micimpact.web.controller;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import javax.annotation.Resource;
import javax.mail.MessagingException;
import javax.mail.internet.AddressException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.http.HttpResponse;
import org.springframework.data.domain.Page;
import org.springframework.security.config.authentication.UserServiceBeanDefinitionParser;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.amazonaws.services.identitymanagement.model.User;
import com.app.micimpact.bean.CardTags;
import com.app.micimpact.bean.Cards;
import com.app.micimpact.bean.Comments;
import com.app.micimpact.bean.Images;
import com.app.micimpact.bean.Resources;
import com.app.micimpact.bean.Users;
import com.app.micimpact.bean.jpa.CardsEntity;
import com.app.micimpact.bean.jpa.CommentsEntity;
import com.app.micimpact.business.service.CardTagsService;
import com.app.micimpact.business.service.CardsService;
import com.app.micimpact.business.service.CommentsService;
import com.app.micimpact.business.service.ImagesService;
import com.app.micimpact.business.service.ResourcesService;
import com.app.micimpact.business.service.UsersService;
//--- Common classes
import com.app.micimpact.web.common.AbstractController;
import com.app.micimpact.web.common.AmazonSES;
import com.app.micimpact.web.common.Pager;
import com.restfb.types.Comment;
//--- Entities
//--- List Items 
//--- Services 


@Controller
@RequestMapping("/")
public class MainController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "posting";
	private static final String MAIN_LIST_NAME   = "list";

	private static final String JSP_MAIN   = "user_main";
	private static final String JSP_ADMIN_SIGN   = "admin_sign";

	private static final String JSP_SHARE_MOBILE   = "share/sys_1";
	private static final String JSP_VIDEO   = "video";
	private static final String JSP_STATS   = "admin/stats";
	
	@Resource
    private ResourcesService recouresService; // Injected by Spring
	@Resource
	private CardsService cardsService;
	@Resource
	private UsersService usersService;
	@Resource
	private CardTagsService cardTagsService;
	@Resource
	private CommentsService commentsService;
	@Resource
	private ImagesService imagesService;
	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public MainController() {
		super(MainController.class, MAIN_ENTITY_NAME );
		log("PostingController created.");
	}

	@RequestMapping("/")
	public String mainPage(Model model, HttpServletRequest request, Locale locale) {
//		log("Action 'main page'");
//		
//		System.out.println("locale : " + locale);
//		List<Resources> resources = new ArrayList<Resources>();
//		if (locale.toString().equals("ko_KR") || locale.toString().equals("en")) {
//			resources = recouresService.findByDomainLikeAndLocale("MONTH", locale.toString());
//		}else{
//			resources = recouresService.findByDomainLike("MONTH");
//		}
//				
//		model.addAttribute("domain_test", resources);
//		securityCheck(model, request);
		
//		twitter login Test
		
		
		
		return "redirect:/login";
	}
	
	
	@RequestMapping("/video/{id}")
	public String admimLogin(
			@PathVariable("id") int id,
			Model model){
		Cards c = cardsService.findById(id);
		model.addAttribute("c", c);
		
		return JSP_VIDEO;
	}
	
	
	

	
	
	@RequestMapping("/share/sys_1/{id}")
	public String share_ios(
			@PathVariable("id") int id,HttpServletResponse response,HttpServletRequest request,
			Model model){
		response.addHeader("Access-Control-Allow-Origin", "*");
		String  browserDetails  =   request.getHeader("User-Agent");
		System.out.println(browserDetails);
		String  userAgent       =   browserDetails;
		CardsEntity c=cardsService.findOne(id);
		model.addAttribute("c", c);
		Users u= usersService.findById(c.getUserId());
		Integer[] card_id = new Integer[1];
		card_id[0]=c.getId();
		try {
			List<CardTags> list= cardTagsService.findByCardIdIn(card_id);
			model.addAttribute("list", list);
		} catch (Exception e) {
			// TODO: handle exception
		}
		System.out.println(browserDetails);
		model.addAttribute("mobile", browserDetails);
			model.addAttribute("android", 2);
		 if (userAgent.toLowerCase().indexOf("android") >= 0 )
         {
			 model.addAttribute("android", 1);
         } else if(userAgent.toLowerCase().indexOf("iphone") >= 0 )
         {
        	 model.addAttribute("android", 0);
        	 
         }
		
		List<Images> images = imagesService.findByCardIdIn(card_id);
		List<Cards> cards=cardsService.findOtherCardByCategoryId(c.getCategoryId(),c.getId(), 2);
		model.addAttribute("total_video",cards.size());
		List<Comments> listComment=commentsService.findByCardId(id, 1);
		model.addAttribute("comment", listComment);
		model.addAttribute("list_image", images);
		model.addAttribute("u", u);
		model.addAttribute("cards", cards);
		model.addAttribute("img", c.getThumbnailUrl());
		model.addAttribute("title", "Micimpact");
		model.addAttribute("site_name", "micimpact.com");
		model.addAttribute("description", "micimpact.com");
		return JSP_SHARE_MOBILE;
	}
	
	
	
	
	
	/**
	 *
	 *  Amazon SES 
	 *  sendmail만 적용.(확실히 적용.)
	 * 
	 */
	@RequestMapping("/sendMail")
	public void testMaile(HttpServletResponse response) throws IOException, AddressException, MessagingException {
		PrintWriter out = response.getWriter();
		
		log("Action 'send mail'");
		
//		AmazonSES ses = new AmazonSES();
//		
//		try {
//			ses.sendMail();
//			out.print("true");
//		} catch (Exception e) {
//			// TODO: handle exception
//			log(e.toString());
//			out.print("false");
//		}
		
	}
}
