<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.1 ) - Date 2015-04-29 ( Time 14:15:53 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>
<%@ taglib tagdir="/WEB-INF/tags/trams" prefix="trams_c"%>

	<div class="container">

		<table class="table row">
			<thead>
				<tr class="active">
					<th class="col-sm-1"><s:message code="board.number"/></th>
					<th class="col-sm-7"><s:message code="board.title"/></th>
					<th class="col-sm-2"><s:message code="board.writer"/></th>
					<th class="col-sm-2"><s:message code="board.createDate"/></th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${list}" var="List" varStatus="listCount">
					<tr>
						<c:choose>
							<c:when test="${List.postingTypes.id == 12}">
								<td><s:message code="board.notice"/></td>
							</c:when>
							<c:otherwise>
								<td>${List.id}</td>
							</c:otherwise>
						</c:choose>
						<td class="title">
							<c:if test="${List.parentId != List.id}">
								<div class="re_mark"></div>
							</c:if> 
							<a	href="${url}/${List.id}">${List.title}</a>
						</td>
						<td>${List.users.name}</td>
						<td><fmt:formatDate
								value="${List.createdAt}" pattern="yyyy-MM-dd" /></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		<trams_c:pagnation currentIndex="${currentIndex}" url="${url}" totalPages="${page.totalPages}" id="" param_url="bType=${bType}"/>
		<c:if test="${bType != 10}">
			<div class="btn-container">
				<a class="btn btn-default" href="${url}/write?bType=${bType}" onclick="return isLogin();"><s:message code="write"/></a>
			</div>
		</c:if> 
		
	</div>	
</div>
<script type="text/javascript">
	function isLogin(){
		if("${member}"== "true"){
			return true;
		}else{
			alert("글쓰기는 로그인 후에 사용 가능합니다.");
			return false;
		}
	}
</script>
