<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.1 ) - Date 2015-04-29 ( Time 14:15:53 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<ul class="list-group">
		  <li class="list-group-item" style="background-color:#f5f5f5;">${posting.title} </li>
		  <li class="list-group-item" style="background-color:#f5f5f5;">작성자: ${posting.users.name}, 작성일: <fmt:formatDate value="${posting.createdAt}" pattern="yyyy-MM-dd"/></li>
		  <li class="list-group-item" style="min-height: 300px;">${posting.body}</li>
		  <c:forEach items="${uploadFiles}" var="List" varStatus="listCount">
		  	<li class="list-group-item" style="background-color:#f5f5f5;"><a href="${url}/uploadFiles/${List.id}">${List.extra1}</a> </li>
		  </c:forEach>
		</ul>
		
		<div class="btn-container">
			<!-- <c:if test="${posting.parentId == posting.id}">
				<a class="btn btn-default" href="${url}/reply/${posting.id}?type=${posting.postingTypes.id}" >답글</a>
			</c:if> -->
			<a class="btn btn-default" href="${url}/modify/${posting.id}" >수정</a>
			<a class="btn btn-default" href="${url}/delete/${posting.id}?bType=${bType}" onclick="return delchk();">삭제</a>
			<a class="btn btn-default" href="${url}?bType=${bType}" >목록</a>
		</div>
		
		
</div>
<script type="text/javascript">
	function submitContents() {
		if (!isEmpty()) {
			return true;
		}else{
			return false;
		}
	}
	function isEmpty() {
		var result = false;
		var body = document.getElementById("body").value;
		if (stringIsEmpty(body)) {
			alert("내용을 입력해 주세요.");
			result = true;
		}
		
		return result;
	}
	function stringIsEmpty(str) {
		var blank_pattern = /^\s+|\s+$/g;

		if (str == '' || str == null) {
			return true;
		} else if (str.replace(blank_pattern, '') == "") {
			return true;
		}

		return false;
	}
	function delchk(){
		if(confirm("삭제 하시겠습니까?")){
			return true;
		}else{
			return false;
		}
	}
</script>
