<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.1 ) - Date 2015-04-29 ( Time 14:15:53 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<form:form class="form-horizontal" action="${url}/update/${posting.id}" modelAttribute="posting" 
		method="POST" id="write-form" onsubmit="return submitContents(this)">
			<form:input type="hidden" path="parentId"/>
			<c:choose>
				<c:when test="${posting.parentId == posting.id && bType == 10}">
					<div class="form-group">
						<label for="posting-type" class="col-sm-1 control-label">글 종류</label>
						<div class="col-sm-11">
							<form:select id="posting-type" path="typeId" class="form-control">
								<form:option value="" selected="selected" style="display: none;">종류를 선택해 주세요.</form:option>
								<form:option value="11" id="11" name="type">일반공지</form:option>
								<form:option value="12" id="12" name="type">중요공지</form:option>
							</form:select>
						</div>
					</div>
				</c:when>
				<c:otherwise>
					<form:input type="hidden" path="typeId" id="posting-type"/>
				</c:otherwise>
			</c:choose>
			<div class="form-group">
				<label for="title" class="col-sm-1 control-label">제목</label>
				<div class="col-sm-11">
					<form:input class="form-control" path="title" id="title"/>	
				</div>
			</div>
			<div class="form-group">
				<label for="body" class="col-sm-1 control-label">내용</label>
				<div class="col-sm-11">
					<form:textarea path="body" id="body" style="width: 100%; height: 350px;" />	
				</div>
			</div>
			<c:if test="${not empty uploadFiles}">
				<div class="form-group">
					<label for="body" class="col-sm-1 control-label">첨부파일</label>
					<div class="col-sm-11">
						<ul class="list-group">
							<c:forEach items="${uploadFiles}" var="List" varStatus="listCount">
						  		<li class="list-group-item" id="${List.id}">
						  			<a href="${url}/uploadFiles/${List.id}">${List.extra1}</a> 
						  			<a class="btn btn-default" href="#" onclick="deleteFile(this)">삭제</a>
						  		</li>
						 	</c:forEach>
						 </ul>
					</div>
				</div>
			</c:if>
			<input type="hidden" id="delete" name="delete" value=""/>
		</form:form >
		<!-- 
			<form:form id="file-form" enctype="multipart/form-data" modelAttribute="fileTransfer" action="${url}/create_files" method="POST">	
				<div class="form-group">
					<label for="body" class="col-sm-1 control-label" >파일 첨부</label>
					<div class="col-sm-11" id="fileInputs">
						<input class="file" type="file" id="file0"  name="files[0]"/>	
					</div>
				</div>
			</form:form>
 		-->
			<input type="hidden" value="0" id="index"/>
				
			<div class="form-group">
				<div class="col-sm-offset-1 col-sm-11 btn-container">
					<button class="btn btn-default" onclick="submitContents();">저장</button>
					<a href="${url}?bType=${bType}" class="btn btn-default">취소</a>
				</div>
			</div>
	</div>	
</div>
<s:url value="/js/board/write.js" var="js_url_write" />
<script type="text/javascript" src="${js_url_write}" charset="UTF-8"></script>
<script type="text/javascript">
	$(document).on("change", "input[type='file']", function(){
		var index = $("#index").val();
		var fileId = $(this).attr('id');
		var fileIndex = fileId.split('file')[1];
		var file = pathToFile($(this).val());
		var fileName = file.name+"."+file.extension;
		var fileNameHtml = '<div>'+fileName+' <span class="glyphicon glyphicon-remove" fileId="'+ fileId +'" onclick="deleteNewFile(this)"></span></div>';
		$(this).addClass('hide');
		$("#fileInputs").append(fileNameHtml);
		addFileInput();
	});
	
	function deleteNewFile(ele){
		var fileId = "#"+$(ele).attr('fileId');
		$(ele).parent().remove();
		$(fileId).remove();
	
		return false;
	}
	function addFileInput(){
		var index = $("#index").val();
		var newIndex = Number(index) + 1;
		$("#index").val(newIndex);
		
		var fileHtml = '<input class="file" name="files['+ newIndex +']" type="file" id="file' + newIndex + '"></input>';
		$("#fileInputs").append(fileHtml);
	}
	function pathToFile(str)
	{
	    var nOffset = Math.max(0, Math.max(str.lastIndexOf('\\'), str.lastIndexOf('/')));
	    var eOffset = str.lastIndexOf('.');
	    if(eOffset < 0)
	    {
	        eOffset = str.length;
	    }
	    return {isDirectory: eOffset == str.length,
	            path: str.substring(0, nOffset),
	            name: str.substring(nOffset > 0 ? nOffset + 1 : nOffset, eOffset),
	            extension: str.substring(eOffset > 0 ? eOffset + 1 : eOffset, str.length)};
	}
	function deleteFile(fPath){
		var delList = $("#delete").val();
		var id = $(fPath).parent().attr('id');
		if(delList != ""){
			$("#delete").val(delList+","+id);
		}else{
			$("#delete").val(id);
		}
		$(fPath).parent().remove();
		return false;
	}
</script>
