<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.1 ) - Date 2015-04-29 ( Time 14:15:53 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>
<%@ taglib tagdir="/WEB-INF/tags/display" prefix="display"%>
<%@ taglib tagdir="/WEB-INF/tags/trams" prefix="trams_c"%>

	<div class="container">
		<div class="container">
		<div class="login-card login_admin" style="margin-top: 0;">
			<h3 style="text-align: center;">관리자 페이지</h3><br>
			<form>
				<table border="0" width="100%">
					<tr>
						<td width="20%"><span class="row">아이디</span></td>
						<td width="80%"><input type="text" name="user_id" placeholder="아이디"></td>
					</tr>
					<tr>
						<td><span class="row">비밀번호</span></td>
						<td><input type="password" name="password" placeholder="비밀번호" onkeypress="if(event.keyCode==13) {signin(); return false;}"></td>
					</tr>
				</table>
				
				
				
				<input type="button" onclick="signin();" name="login" class="login login-submit" value="login">
			</form>
		    
			<div class="login-help">
				<a href="/reserved"><s:message code="login.lost_title"/></a>
			</div>
		
			<!-- <BUTTON id="sendMail" type="button">메일보내기</BUTTON> -->
			<script type="text/javascript">
				function signin() {
			        $.ajax({
			             url : root+'j_spring_security_check',
			             data: $('form input').serialize(),
			             type: 'POST',
			             dataType : 'json',
			             beforeSend: function(xhr) {
			                  xhr.setRequestHeader("Accept", "application/json");
			             }
			        }).done(function(body) {
			        	
			        	 var message = body.message;
			             var success = body.success;
			             var type = body.type;
			             			             
			             if (!success){
			            	 alert(message);
			             }
			
			             if (success) {
			                  var url = '${referer}';
			                  if (url == ''){
			                	  switch (type) {
									case 1:
										url = '<c:url value="/admin" />';
										break;
									case 2:
										url = '<c:url value="/res" />';
										break;

									default:
										url = '<c:url value="/" />';
										break;
								}
			                	  
			                  }
			                  location.href = url;
			             }
			
			        });
			
			   }
				
				$(document).ready(function(){
				    // 저장된 쿠키값을 가져와서 ID 칸에 넣어준다. 없으면 공백으로 들어감.
				    var userInputId = getCookie("userInputId");
					$("input[name='user_id']").val(userInputId); 
					
				    if($("input[name='user_id']").val() != ""){ // 그 전에 ID를 저장해서 처음 페이지 로딩 시, 입력 칸에 저장된 ID가 표시된 상태라면,
				        $("#idSaveCheck").attr("checked", true); // ID 저장하기를 체크 상태로 두기.
				    }
				     
				    $("#idSaveCheck").change(function(){ // 체크박스에 변화가 있다면,
				        if($("#idSaveCheck").is(":checked")){ // ID 저장하기 체크했을 때,
				            var userInputId = $("input[name='user_id']").val();
				            setCookie("userInputId", userInputId, 7); // 7일 동안 쿠키 보관
				        }else{ // ID 저장하기 체크 해제 시,
				            deleteCookie("userInputId");
				        }
				    });
				     
				    // ID 저장하기를 체크한 상태에서 ID를 입력하는 경우, 이럴 때도 쿠키 저장.
				    $("input[name='user_id']").keyup(function(){ // ID 입력 칸에 ID를 입력할 때,
				        if($("#idSaveCheck").is(":checked")){ // ID 저장하기를 체크한 상태라면,
				            var userInputId = $("input[name='user_id']").val();
				            setCookie("userInputId", userInputId, 7); // 7일 동안 쿠키 보관
				        }
				    });
				});
				 
				function setCookie(cookieName, value, exdays){
				    var exdate = new Date();
				    exdate.setDate(exdate.getDate() + exdays);
				    var cookieValue = escape(value) + ((exdays==null) ? "" : "; expires=" + exdate.toGMTString());
				    document.cookie = cookieName + "=" + cookieValue;
				}
				 
				function deleteCookie(cookieName){
				    var expireDate = new Date();
				    expireDate.setDate(expireDate.getDate() - 1);
				    document.cookie = cookieName + "= " + "; expires=" + expireDate.toGMTString();
				}
				 
				function getCookie(cookieName) {
				    cookieName = cookieName + '=';
				    var cookieData = document.cookie;
				    var start = cookieData.indexOf(cookieName);
				    var cookieValue = '';
				    if(start != -1){
				        start += cookieName.length;
				        var end = cookieData.indexOf(';', start);
				        if(end == -1)end = cookieData.length;
				        cookieValue = cookieData.substring(start, end);
				    }
				    return unescape(cookieValue);
				}
						</script>
		</div>
	</div>	
	</div>
</div>
