<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.0 ) - Date 2015-12-09 ( Time 16:26:40 ) -->

<div>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/display" prefix="display"%>


	<div class="container">
		<fieldset class="col-sm-12 bordure">
			<legend class="legende"><s:message code="cards"/></legend>
		
			<util:message message="${message}" messages="${messages}" />

			<table class="table table-striped">
				<thead>
					<tr>
						<th><s:message code="cards.id"/></th>
						<th><s:message code="cards.userId"/></th>
						<th><s:message code="cards.categoryId"/></th>
						<th><s:message code="cards.thumbnailUrl"/></th>
						<th><s:message code="cards.targetUrl"/></th>
						<th><s:message code="cards.title"/></th>
						<th><s:message code="cards.body"/></th>
						<th><s:message code="cards.type"/></th>
						<th><s:message code="cards.countLike"/></th>
						<th><s:message code="cards.share"/></th>
						<th><s:message code="cards.runingTime"/></th>
						<th><s:message code="cards.createdAt"/></th>
						<th><s:message code="cards.adIs"/></th>
						<th><s:message code="cards.adMent"/></th>
						<th><s:message code="cards.adLink"/></th>
						<th><s:message code="cards.relatedCardId"/></th>
						<s:url var="url_create" value="/cards/form"  />
						<th><a class="btn btn-info" href='${url_create}'><s:message code="create"/></a></th>
					</tr>
				</thead>
				<tbody>
					<c:forEach items="${list}" var="cards">
						<tr>
							<td>${cards.id}</td>
							<td>${cards.userId}</td>
							<td>${cards.categoryId}</td>
							<td>${cards.thumbnailUrl}</td>
							<td>${cards.targetUrl}</td>
							<td>${cards.title}</td>
							<td>${cards.body}</td>
							<td>${cards.type}</td>
							<td>${cards.countLike}</td>
							<td>${cards.share}</td>
							<td>${cards.runingTime}</td>
							<td><display:date value="${cards.createdAt}" /></td>
							<td>${cards.adIs}</td>
							<td>${cards.adMent}</td>
							<td>${cards.adLink}</td>
							<td>${cards.relatedCardId}</td>
							<s:url var="url_update" value="/cards/form/${cards.id}"/>
							<td><a class="btn btn-info" href="${url_update}"><s:message code="edit"/></a></td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</fieldset>
	</div>
</div>