<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.0 ) - Date 2015-12-09 ( Time 16:26:40 ) -->

<div>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<fieldset class="col-sm-12 bordure">
			<legend class="legende"><s:message code="cards"/></legend>
		
			<util:message message="${message}" messages="${messages}" />
			
	    	<s:url value="${saveAction}" var="url_form_submit" />
			<form:form class="form-horizontal" modelAttribute="cards" cssClass="well form-horizontal" method="POST" action="${url_form_submit}">
				<form:errors path="*" cssClass="alert alert-danger" element="div" />

<c:if test="${mode != 'create'}">
				<!-- Store data in hidden fields in order to be POST even if the field is disabled -->
				<form:hidden path="id" />
</c:if>
 
				<!-- PRIMARY KEY FIELD : id -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_id" class="col-sm-2 control-label"><s:message code="cards.id"/></label>
					<div class="col-sm-10">
						<form:input id="cards_id" path="id" class="form-control" maxLength="11" disabled="${mode != 'create'}" />
						<form:errors id="cards_id_errors" path="id" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : userId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_userId" class="col-sm-2 control-label"><s:message code="cards.userId"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_userId" path="userId" class="form-control" maxLength="11"  />
						<form:errors id="cards_userId_errors" path="userId" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : categoryId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_categoryId" class="col-sm-2 control-label"><s:message code="cards.categoryId"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_categoryId" path="categoryId" class="form-control" maxLength="11"  />
						<form:errors id="cards_categoryId_errors" path="categoryId" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : thumbnailUrl -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_thumbnailUrl" class="col-sm-2 control-label"><s:message code="cards.thumbnailUrl"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_thumbnailUrl" path="thumbnailUrl" class="form-control" maxLength="256"  />
						<form:errors id="cards_thumbnailUrl_errors" path="thumbnailUrl" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : targetUrl -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_targetUrl" class="col-sm-2 control-label"><s:message code="cards.targetUrl"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_targetUrl" path="targetUrl" class="form-control" maxLength="256"  />
						<form:errors id="cards_targetUrl_errors" path="targetUrl" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : title -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_title" class="col-sm-2 control-label"><s:message code="cards.title"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_title" path="title" class="form-control" maxLength="256"  />
						<form:errors id="cards_title_errors" path="title" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : body -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_body" class="col-sm-2 control-label"><s:message code="cards.body"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_body" path="body" class="form-control" maxLength="512"  />
						<form:errors id="cards_body_errors" path="body" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : type -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_type" class="col-sm-2 control-label"><s:message code="cards.type"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_type" path="type" class="form-control" maxLength="11"  />
						<form:errors id="cards_type_errors" path="type" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : countLike -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_countLike" class="col-sm-2 control-label"><s:message code="cards.countLike"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_countLike" path="countLike" class="form-control" maxLength="11"  />
						<form:errors id="cards_countLike_errors" path="countLike" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : share -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_share" class="col-sm-2 control-label"><s:message code="cards.share"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_share" path="share" class="form-control" maxLength="11"  />
						<form:errors id="cards_share_errors" path="share" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : runingTime -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_runingTime" class="col-sm-2 control-label"><s:message code="cards.runingTime"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_runingTime" path="runingTime" class="form-control" maxLength="11"  />
						<form:errors id="cards_runingTime_errors" path="runingTime" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : createdAt -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_createdAt" class="col-sm-2 control-label"><s:message code="cards.createdAt"/></label>
					<div class="col-sm-10">
  						<input:date id="cards_createdAt" name="createdAt" />  <!-- DATE type -->
						<form:errors id="cards_createdAt_errors" path="createdAt" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : adIs -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_adIs" class="col-sm-2 control-label"><s:message code="cards.adIs"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_adIs" path="adIs" class="form-control" maxLength="11"  />
						<form:errors id="cards_adIs_errors" path="adIs" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : adMent -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_adMent" class="col-sm-2 control-label"><s:message code="cards.adMent"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_adMent" path="adMent" class="form-control" maxLength="128"  />
						<form:errors id="cards_adMent_errors" path="adMent" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : adLink -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_adLink" class="col-sm-2 control-label"><s:message code="cards.adLink"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_adLink" path="adLink" class="form-control" maxLength="256"  />
						<form:errors id="cards_adLink_errors" path="adLink" cssClass="label label-danger" />

					</div>
				</div>

 
				<!-- DATA FIELD : relatedCardId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="cards_relatedCardId" class="col-sm-2 control-label"><s:message code="cards.relatedCardId"/></label>
					<div class="col-sm-10">
  						<form:input id="cards_relatedCardId" path="relatedCardId" class="form-control" maxLength="11"  />
						<form:errors id="cards_relatedCardId_errors" path="relatedCardId" cssClass="label label-danger" />

					</div>
				</div>

 

				<!-- ACTION BUTTONS -->
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-2">
						<c:if test="${mode != 'create'}">
							<!-- "DELETE" button ( HREF link ) -->
							<s:url var="deleteButtonURL" value="/cards/delete/${cards.id}" />
							<a role="button" class="btn btn-danger btn-block" href="${deleteButtonURL}"><s:message code="delete"/></a>
						</c:if>
					</div>
    				<div class="col-sm-offset-4 col-sm-2">
						<!-- "CANCEL" button ( HREF link ) -->
		 				<s:url var="cancelButtonURL" value="/cards" />
						<a role="button" class="btn btn-default btn-block" href="${cancelButtonURL}"><s:message code="cancel"/></a>
					</div>
    				<div class="col-sm-2">
						<!-- "SAVE" button ( SUBMIT button ) -->
						<button type="submit" class="btn btn-primary btn-lg btn-block"><s:message code="save"/></button>
					</div>
				</div>
			</form:form>
	    </fieldset>
	</div>	
</div>
