<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.1 ) - Date 2015-04-29 ( Time 14:15:53 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>
<%@ taglib tagdir="/WEB-INF/tags/trams" prefix="trams_c"%>

	<div class="container">
		<div style="margin-bottom: 25px;">
			 <legend class="legende">팝업 관리
			 	<div class="search_box">
					<div class="row">
						<select class="form-control" id="options">
							<option value="1" selected="selected">name</option>
						</select>
						<div class="col-lg-6" >
							<div class="input-group">
								<span class="input-group-addon" id="sizing-addon1">
									<span class="glyphicon glyphicon-search"></span>
								</span>
								<input type="text" name="keyword" class="form-control" placeholder=""  onkeypress="if(event.keyCode==13) {search(); return false;}">
								<span class="input-group-btn">
									<button class="btn btn-default" type="button" onclick="search()">검색</button>
									<button class="btn btn-default" type="button" onclick="register()">등록</button>
								</span>
							</div><!-- /input-group -->
						</div><!-- /.col-lg-6 -->
					</div><!-- /.row -->
				</div>
			</legend>
		</div>
		<table class="table table-bordered">
			<thead>
			    <tr>
			      <th>id</th>
			      <th>팝업명</th>
			      <th>언어</th>
			      <th>시작일자</th>
			      <th>종료일자</th>
			      <th>미리보기</th>
			      <th>삭제</th>
			    </tr>
			</thead>
			<tbody>
			    <c:forEach items="${list}" var="popups">
					<tr>
						<td>${popups.id}</td>
						<td>${popups.name}</td>
						<td>${popups.locale}</td>
						<td><fmt:formatDate
								value="${popups.startAt}" pattern="yyyy-MM-dd" /></td>
						<td><fmt:formatDate
								value="${popups.endAt}" pattern="yyyy-MM-dd" /></td>
						<td><a href="javascript:CaricaFoto('${popups.imageUrl}', '${popups.id}')" BORDER="0">보기</a></td>
						<td><a class="btn btn-default" href="/admin/popup/delete/${popups.id}" >삭제</a></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		<trams_c:pagnation currentIndex="${currentIndex}" url="${url}" totalPages="${page.totalPages}" id="" />
	</div>
</div>
<script type="text/javascript">
$(function(){
	if (GetQueryStringParams('option')!=null)
	{
		$('#options option[value="'+GetQueryStringParams('option')+'"]').attr("selected",true);
	}
	
	if (GetQueryStringParams('keyword')!=null)
	{
		$("input[name=keyword]").val(GetQueryStringParams('keyword'))
	}
});
function search() {
	var option = $("#options").val();
	var keyword = $("input[name=keyword]").val();
	
	if (keyword.length > 0 && option != 0 ){
		var url = "/admin/popup/search?option="+ option + "&keyword=" + keyword;
		location.href = url;
	}else {
		location.href = "/admin/popup/";
	}
}

function register() {
	location.href = "/admin/popup/register"
}

function popupShow(id) {
	var popOption = "width=370, height=360, resizable=no, scrollbars=no, status=no;";    //팝업창 옵션(optoin)
	window.open(popUrl, "", popOption);
}

var popupId;

function CaricaFoto(img, id) { 
	popupId = id;
	foto1= new Image(); 
	foto1.src=(img); 
	Controlla(img); 
} 
function Controlla(img) { 
	if((foto1.width!=0)&&(foto1.height!=0)) { 
		viewFoto(img); 
	}else { 
		funzione="Controlla('"+img+"')"; 
		intervallo=setTimeout(funzione,20); 
	} 
} 
function viewFoto(img) { 
	var popUrl = "/admin/popup/show?id="+ popupId;
	largh=foto1.width+20; 
	altez=foto1.height+25; 
	stringa="width="+largh+",height="+altez; 
	finestra=window.open(popUrl,"",stringa); 
} 
</script>

