<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 2.1.1 ) - Date 2015-04-29 ( Time 14:15:53 ) -->

<div class="wrap">
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<form:form class="form-horizontal" action="/admin/popup/register/complete" modelAttribute="popup" 
		method="POST" id="write-form" enctype="multipart/form-data">
		<div>
			 <legend class="legende">팝업 등록</legend>
			<table class="table table-bordered">
				<thead>
				    <tr>
				      <th>팝업명</th>
				      <th>언어</th>
				      <th>팝업이미지</th>
				      <th>시작일자</th>
				      <th>종료일자</th>
				    </tr>
				</thead>
				<tbody>
				    <tr>
				    	<td><form:input  type="text" class="form-control" placeholder="팝업명" path="name" id="name"/></td>
				    	<td>
				    		<form:select  type="text" class="form-control" placeholder="언어" path="locale" id="locale">
				    			<c:forEach items="${locales}" var="locale">
				    				<option value = "${locale.value}">${locale.language}</option>
				    			</c:forEach>
				    		</form:select>
				    	</td>
				    	<td><input type="file" name="popup_image" required="required" title="팝업이미지 업로드" id="popup_image"/></td>
				    	<td><input  type="text" name="start_date" class="form-control" placeholder="시작일자" id="startAt"/></td>
				    	<td><input  type="text" name="end_date" class="form-control" placeholder="종료일자" id="endAt"/></td>
				    </tr>
				</tbody>
			</table>
			<div class="form-group" style="float: right; width: 156px;">
				<div class="col-sm-offset-1 col-sm-11">
					<button class="btn btn-default" type="submit">저장</button>
					<a href="/admin/popup" class="btn btn-default">취소</a>
				</div>
			</div>
		</div>
		</form:form>
	</div>
</div>
<SCRIPT type="text/javascript">
	$(function(){
		$("#startAt").datepicker({format: 'yyyy-mm-dd'}).on('changeDate', function(ev){
			var newDate = new Date(ev.date);
			newDate.setDate(newDate.getDate());
			$("#startAt").val(getFormattedDate(newDate));
		});
		$("#endAt").datepicker({format: 'yyyy-mm-dd'}).on('changeDate', function(ev){
			var newDate = new Date(ev.date);
			newDate.setDate(newDate.getDate());
			$("#endAt").val(getFormattedDate(newDate));
		});
		// 날짜 초기 작업
		$("#dp1").val(getFormattedDate(d));
	});
	
    
</SCRIPT>