/*
 * Created on 30 Mar 2016 ( Time 14:45:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.app.micimpact.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.app.micimpact.bean.Cards;
import com.app.micimpact.bean.jpa.CardsEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CardsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CardsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CardsEntity' to 'Cards'
	 * @param cardsEntity
	 */
	public Cards mapCardsEntityToCards(CardsEntity cardsEntity) {
		if(cardsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Cards cards = map(cardsEntity, Cards.class);

		return cards;
	}
	
	/**
	 * Mapping from 'Cards' to 'CardsEntity'
	 * @param cards
	 * @param cardsEntity
	 */
	public void mapCardsToCardsEntity(Cards cards, CardsEntity cardsEntity) {
		if(cards == null) {
			return;
		}

		//--- Generic mapping 
		map(cards, cardsEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}