/*
 * Created on 21 12월 2015 ( Time 19:49:29 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.app.micimpact.bean.CardTags;
import com.app.micimpact.bean.jpa.CardTagsEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CardTagsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CardTagsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CardTagsEntity' to 'CardTags'
	 * @param cardTagsEntity
	 */
	public CardTags mapCardTagsEntityToCardTags(CardTagsEntity cardTagsEntity) {
		if(cardTagsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		CardTags cardTags = map(cardTagsEntity, CardTags.class);

		return cardTags;
	}
	
	/**
	 * Mapping from 'CardTags' to 'CardTagsEntity'
	 * @param cardTags
	 * @param cardTagsEntity
	 */
	public void mapCardTagsToCardTagsEntity(CardTags cardTags, CardTagsEntity cardTagsEntity) {
		if(cardTags == null) {
			return;
		}

		//--- Generic mapping 
		map(cardTags, cardTagsEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}