/*
 * Created on 28 12월 2015 ( Time 18:22:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.app.micimpact.bean.CommentLikes;
import com.app.micimpact.bean.jpa.CommentLikesEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CommentLikesServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CommentLikesServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CommentLikesEntity' to 'CommentLikes'
	 * @param commentLikesEntity
	 */
	public CommentLikes mapCommentLikesEntityToCommentLikes(CommentLikesEntity commentLikesEntity) {
		if(commentLikesEntity == null) {
			return null;
		}

		//--- Generic mapping 
		CommentLikes commentLikes = map(commentLikesEntity, CommentLikes.class);

		return commentLikes;
	}
	
	/**
	 * Mapping from 'CommentLikes' to 'CommentLikesEntity'
	 * @param commentLikes
	 * @param commentLikesEntity
	 */
	public void mapCommentLikesToCommentLikesEntity(CommentLikes commentLikes, CommentLikesEntity commentLikesEntity) {
		if(commentLikes == null) {
			return;
		}

		//--- Generic mapping 
		map(commentLikes, commentLikesEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}