/*
 * Created on 9 12월 2015 ( Time 17:41:16 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.app.micimpact.bean.Images;
import com.app.micimpact.bean.jpa.ImagesEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ImagesServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ImagesServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ImagesEntity' to 'Images'
	 * @param imagesEntity
	 */
	public Images mapImagesEntityToImages(ImagesEntity imagesEntity) {
		if(imagesEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Images images = map(imagesEntity, Images.class);

		return images;
	}
	
	/**
	 * Mapping from 'Images' to 'ImagesEntity'
	 * @param images
	 * @param imagesEntity
	 */
	public void mapImagesToImagesEntity(Images images, ImagesEntity imagesEntity) {
		if(images == null) {
			return;
		}

		//--- Generic mapping 
		map(images, imagesEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}