/*
 * Created on 21 12월 2015 ( Time 20:29:14 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.app.micimpact.bean.Likes;
import com.app.micimpact.bean.jpa.LikesEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class LikesServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public LikesServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'LikesEntity' to 'Likes'
	 * @param likesEntity
	 */
	public Likes mapLikesEntityToLikes(LikesEntity likesEntity) {
		if(likesEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Likes likes = map(likesEntity, Likes.class);

		return likes;
	}
	
	/**
	 * Mapping from 'Likes' to 'LikesEntity'
	 * @param likes
	 * @param likesEntity
	 */
	public void mapLikesToLikesEntity(Likes likes, LikesEntity likesEntity) {
		if(likes == null) {
			return;
		}

		//--- Generic mapping 
		map(likes, likesEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}