/*
 * Created on 21 12월 2015 ( Time 20:29:14 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.app.micimpact.bean.ListCards;
import com.app.micimpact.bean.jpa.ListCardsEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ListCardsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ListCardsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ListCardsEntity' to 'ListCards'
	 * @param listCardsEntity
	 */
	public ListCards mapListCardsEntityToListCards(ListCardsEntity listCardsEntity) {
		if(listCardsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ListCards listCards = map(listCardsEntity, ListCards.class);

		return listCards;
	}
	
	/**
	 * Mapping from 'ListCards' to 'ListCardsEntity'
	 * @param listCards
	 * @param listCardsEntity
	 */
	public void mapListCardsToListCardsEntity(ListCards listCards, ListCardsEntity listCardsEntity) {
		if(listCards == null) {
			return;
		}

		//--- Generic mapping 
		map(listCards, listCardsEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}