/*
 * Created on 20 5�� 2015 ( Time 17:27:55 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.app.micimpact.bean.Popups;
import com.app.micimpact.bean.jpa.PopupsEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PopupsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PopupsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PopupsEntity' to 'Popups'
	 * @param popupsEntity
	 */
	public Popups mapPopupsEntityToPopups(PopupsEntity popupsEntity) {
		if(popupsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Popups popups = map(popupsEntity, Popups.class);

		return popups;
	}
	
	/**
	 * Mapping from 'Popups' to 'PopupsEntity'
	 * @param popups
	 * @param popupsEntity
	 */
	public void mapPopupsToPopupsEntity(Popups popups, PopupsEntity popupsEntity) {
		if(popups == null) {
			return;
		}

		//--- Generic mapping 
		map(popups, popupsEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}