/*
 * Created on 21 12월 2015 ( Time 20:29:14 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.app.micimpact.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.app.micimpact.bean.SearchTags;
import com.app.micimpact.bean.jpa.SearchTagsEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class SearchTagsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public SearchTagsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'SearchTagsEntity' to 'SearchTags'
	 * @param searchTagsEntity
	 */
	public SearchTags mapSearchTagsEntityToSearchTags(SearchTagsEntity searchTagsEntity) {
		if(searchTagsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		SearchTags searchTags = map(searchTagsEntity, SearchTags.class);

		return searchTags;
	}
	
	/**
	 * Mapping from 'SearchTags' to 'SearchTagsEntity'
	 * @param searchTags
	 * @param searchTagsEntity
	 */
	public void mapSearchTagsToSearchTagsEntity(SearchTags searchTags, SearchTagsEntity searchTagsEntity) {
		if(searchTags == null) {
			return;
		}

		//--- Generic mapping 
		map(searchTags, searchTagsEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}